server:
  port: 8081
  servlet:
    context-path: /zjmzxfzhl
    compression:
      enabled: true
      mime-types: application/javascript,application/json,application/xml,text/html,text/xml,text/plain,text/css,image/*
spring:
  profiles:
    active: dev #环境 dev|test|prod
  mvc:
    static-path-pattern: /**
  resource:
    #自定义静态资源路径,处理方式见WebMvcConfig.java
    static-locations: classpath:/static/,classpath:/public/
#mybatis plus 设置
mybatis-plus:
  mapper-locations: classpath*:com/**/mapper/xml/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zjmzxfzhl.modules.*.entity
  #configuration: #打印sql
  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
#springboot监控actuator
management:
  endpoints:
    web:
      exposure:
        #include: "*" 
        include: info,metrics,httptrace
# 描述信息
info: 
  blog-url: http://www.test.com
  author: zjm
  version: 1.0
flowable:
  async-executor-activate: false
flowableFontName: 宋体
async:
  executor:
    thread:
     core-pool-size: 10
     max-pool-size: 20
     queue-capacity: 2000
     name-prefix: async-service-
     keep-alive-seconds: 60
# 需要验证验证码的client_id,以逗号隔开
captchaFilter:
  clients: zjmzxfzhl